name: Fantasy reporte

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5" # jueves 8pm AST
    - cron: "0 14 * * 0" # domingo 10am AST

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar
        run: pip install -r requirements.txt

      - name: Enviar reporte
        env:
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          YEAR: ${{ secrets.YEAR }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_report.py
