name: Fantasy reporte

on:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar
        run: pip install -r requirements.txt

      - name: Debug vars
        run: |
          echo "var league empty? ${{ vars.LEAGUE_ID == '' }}"
          echo "secret token empty? ${{ secrets.TELEGRAM_TOKEN == '' }}"

      - name: Enviar reporte
        env:
          LEAGUE_ID: "1884225720"
          YEAR: "2026"
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          ELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "python sees LEAGUE_ID? ${LEAGUE_ID:+yes}"
          python send_report.py
